import { defineType } from "sanity";

export default defineType({
  name: "home",
  title: "Home Page",
  type: "document",
  fields: [
    {
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      description: "Main headline on the homepage hero.",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "heroSubtitle",
      title: "Hero Subtitle",
      type: "text",
      rows: 3,
      description: "Subtitle paragraph displayed under the hero headline.",
    },
    {
      name: "ctaLabel",
      title: "Primary Button Text",
      type: "string",
      description: "e.g. 'View Selected Work'",
    },
    {
      name: "ctaUrl",
      title: "Primary Button URL / Anchor",
      type: "string",
      description: "e.g. '#portfolio' or '/portfolio'",
    },
    {
      name: "secondaryCtaLabel",
      title: "Secondary Button Text",
      type: "string",
      description: "e.g. 'Get In Touch'",
    },
    {
      name: "secondaryCtaUrl",
      title: "Secondary Button URL / Anchor",
      type: "string",
      description: "e.g. '#contact' or '/contact'",
    },
    {
      name: "scrollLabel",
      title: "Scroll Down Label",
      type: "string",
      description: "e.g. 'Scroll Down'",
    },
    {
      name: "servicesKicker",
      title: "Services Section - Kicker",
      type: "string",
      description: "e.g. 'What we do'",
    },
    {
      name: "servicesTitle",
      title: "Services Section - Title",
      type: "string",
      description: "e.g. 'Services engineered for impact.'",
    },
    {
      name: "servicesDescription",
      title: "Services Section - Description",
      type: "text",
      rows: 2,
    },
    {
      name: "skillsKicker",
      title: "Skills Section - Kicker",
      type: "string",
      description: "e.g. 'Skills & Stack'",
    },
    {
      name: "skillsTitle",
      title: "Skills Section - Title",
      type: "string",
      description: "e.g. 'Engineered with precision & modern technology.'",
    },
    {
      name: "skillsDescription",
      title: "Skills Section - Description",
      type: "text",
      rows: 2,
    },
    {
      name: "portfolioKicker",
      title: "Portfolio Section - Kicker",
      type: "string",
      description: "e.g. 'Selected work'",
    },
    {
      name: "portfolioTitle",
      title: "Portfolio Section - Title",
      type: "string",
      description: "e.g. 'Crafted for scale.'",
    },
    {
      name: "testimonialsKicker",
      title: "Testimonials Section - Kicker",
      type: "string",
      description: "e.g. 'Customer voices'",
    },
    {
      name: "testimonialsTitle",
      title: "Testimonials Section - Title",
      type: "string",
      description: "e.g. 'Trusted by teams worldwide.'",
    },
    {
      name: "blogKicker",
      title: "Blog Section - Kicker",
      type: "string",
      description: "e.g. 'Journal'",
    },
    {
      name: "blogTitle",
      title: "Blog Section - Title",
      type: "string",
      description: "e.g. 'Insights & field notes.'",
    },
  ],
});
